### PR TITLE
update to angular v6

### PR DESCRIPTION
**Pull request by andrasczeh**
I've upgraded to angular 6, and applied a workaround in polyfills.ts. Nice project by the way!

### CODE REVIEW

**Comment by narve** [comment]
Hi @andrasczeh thanks a lot for this contribution, and sorry for the late reply! 

I tried to merge this PR but it doesn't seem to work in production builds with the other commits in my project (possibly bpmn-js lib updates from https://github.com/narve/angular-bpmn/issues/4). Could you take a look at https://github.com/narve/angular-bpmn/tree/andrasczeh-master and see if you spot the problem?

**Comment by andrasczeh** [comment]
Hi, sorry for the late reply. I looked into it and seems to be an issue with the angular buildoptimizer. https://github.com/angular/angular-cli/issues/10655
A workaround would be to disable it, but I will try to find a real solution within a few days.

**Comment by besteban1989** [comment]
Hi guys, I've been trying to make this work for an angular 6 version but no success. 
In dev time works great, but when I build it for production then I get this error: 

`
main.72aee93….js:1 ERROR TypeError: this._createContainer is not a function
    at ap.on (main.72aee93….js:1)
    at new ap (main.72aee93….js:1)
    at t.ngOnInit (main.72aee93….js:1)
    at main.72aee93….js:1
    at main.72aee93….js:1
    at Zi (main.72aee93….js:1)
    at Oo (main.72aee93….js:1)
    at Object.updateDirectives (main.72aee93….js:1)
    at Object.updateDirectives (main.72aee93….js:1)
    at Ki (main.72aee93….js:1)`

**Comment by narve** [comment]
Master is now upgraded to Angular 7, with the same bug (createContainer) in production mode. Production mode is not really a requirement so I'm just ignoring it for now.

**Pull request closed without merging**
